pipeline: 
  - module: start_module
    inputs: []
    output_name: request
  - module: code_planner
    inputs: [request]
    supplement: "Use only python."
    output_name: code_plan
  - module: engineer
    inputs: [code_plan]
    output_name: code
